create schema if not exists rogernort;

create table if not exists rogernort.agent_conversations (
  id bigint generated by default as identity primary key,
  session_id text not null,
  user_message text not null,
  assistant_message text not null,
  provider text not null,
  model text,
  handoff_recommended boolean not null default false,
  redactions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists agent_conversations_session_created_idx
  on rogernort.agent_conversations (session_id, created_at desc);

create index if not exists agent_conversations_handoff_idx
  on rogernort.agent_conversations (handoff_recommended, created_at desc)
  where handoff_recommended = true;

alter table rogernort.agent_conversations enable row level security;

comment on table rogernort.agent_conversations is
  'Redacted customer/agent exchanges written only by the backend service role.';
