-- TikTok assistant: connected account tokens, DM conversations, and comment
-- replies. Written only by the backend service role. Message bodies are stored
-- after sensitive-data redaction; raw contact details only reach rogernort.leads.
create schema if not exists rogernort;

create table if not exists rogernort.tiktok_accounts (
  business_id text primary key,
  username text,
  access_token_enc text not null,
  refresh_token_enc text not null,
  access_expires_at timestamptz not null,
  refresh_expires_at timestamptz not null,
  scope text,
  updated_at timestamptz not null default now()
);

create table if not exists rogernort.tiktok_conversations (
  conversation_id text primary key,
  business_id text not null,
  customer_id text,
  customer_name text,
  -- Once a person replies from the TikTok app this is set and never cleared by
  -- the backend: the assistant stays silent in that conversation permanently.
  human_takeover boolean not null default false,
  human_takeover_at timestamptz,
  lead_captured_at timestamptz,
  last_customer_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists rogernort.tiktok_messages (
  id bigint generated by default as identity primary key,
  conversation_id text not null references rogernort.tiktok_conversations (conversation_id) on delete cascade,
  message_id text unique,
  sender text not null check (sender in ('customer', 'assistant', 'human')),
  body text not null default '',
  body_hash text,
  redactions jsonb not null default '[]'::jsonb,
  provider text,
  model text,
  created_at timestamptz not null default now()
);

create index if not exists tiktok_messages_conversation_created_idx
  on rogernort.tiktok_messages (conversation_id, created_at desc);

create table if not exists rogernort.tiktok_comments (
  comment_id text primary key,
  video_id text not null,
  commenter_id text,
  body text not null default '',
  outcome text not null default 'pending'
    check (outcome in ('pending', 'replied', 'skipped', 'failed')),
  skip_reason text,
  reply_comment_id text,
  reply_text text,
  lead_captured boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists tiktok_comments_commenter_video_idx
  on rogernort.tiktok_comments (commenter_id, video_id, created_at desc);

alter table rogernort.tiktok_accounts enable row level security;
alter table rogernort.tiktok_conversations enable row level security;
alter table rogernort.tiktok_messages enable row level security;
alter table rogernort.tiktok_comments enable row level security;

revoke all on table rogernort.tiktok_accounts from public;
revoke all on table rogernort.tiktok_conversations from public;
revoke all on table rogernort.tiktok_messages from public;
revoke all on table rogernort.tiktok_comments from public;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table rogernort.tiktok_accounts, rogernort.tiktok_conversations, rogernort.tiktok_messages, rogernort.tiktok_comments from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table rogernort.tiktok_accounts, rogernort.tiktok_conversations, rogernort.tiktok_messages, rogernort.tiktok_comments from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant usage on schema rogernort to service_role';
    execute 'grant select, insert, update, delete on table rogernort.tiktok_accounts, rogernort.tiktok_conversations, rogernort.tiktok_messages, rogernort.tiktok_comments to service_role';
    execute 'grant usage, select on all sequences in schema rogernort to service_role';
  end if;
end;
$$;

comment on table rogernort.tiktok_accounts is
  'Connected TikTok Business account. Tokens are AES-256-GCM encrypted by the API.';
comment on table rogernort.tiktok_conversations is
  'TikTok DM conversations. human_takeover=true permanently silences the assistant.';
comment on table rogernort.tiktok_messages is
  'Redacted TikTok DM messages, used for assistant context and takeover detection.';
comment on table rogernort.tiktok_comments is
  'TikTok comments seen by the assistant and whether it replied.';
